// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransmissionStockApp.Data;

#nullable disable

namespace TransmissionStockApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Turkish_CI_AS")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransmissionStockApp.Models.Entities.StockLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ShelfCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ShelfCode")
                        .IsUnique();

                    b.ToTable("StockLocations");
                });

            modelBuilder.Entity("TransmissionStockApp.Models.Entities.TransmissionBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TransmissionBrands");
                });

            modelBuilder.Entity("TransmissionStockApp.Models.Entities.TransmissionDriveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TransmissionDriveTypes");
                });

            modelBuilder.Entity("TransmissionStockApp.Models.Entities.TransmissionStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TransmissionStatuses");
                });

            modelBuilder.Entity("TransmissionStockApp.Models.Entities.TransmissionStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SparePartNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TransmissionBrandId")
                        .HasColumnType("int");

                    b.Property<string>("TransmissionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TransmissionDriveTypeId")
                        .HasColumnType("int");

                    b.Property<string>("TransmissionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransmissionStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleBrandId")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleModelId")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TransmissionDriveTypeId");

                    b.HasIndex("TransmissionStatusId");

                    b.HasIndex("VehicleBrandId");

                    b.HasIndex("VehicleModelId");

                    b.HasIndex("TransmissionBrandId", "SparePartNo", "TransmissionStatusId")
                        .IsUnique();

                    b.ToTable("TransmissionStocks");
                });

            modelBuilder.Entity("TransmissionStockApp.Models.Entities.TransmissionStockLocation", b =>
                {
                    b.Property<int>("TransmissionStockId")
                        .HasColumnType("int");

                    b.Property<int>("StockLocationId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("TransmissionStockId", "StockLocationId");

                    b.HasIndex("StockLocationId");

                    b.ToTable("TransmissionStockLocations", t =>
                        {
                            t.HasCheckConstraint("CK_TSL_Quantity_NonNegative", "[Quantity] >= 0");
                        });
                });

            modelBuilder.Entity("TransmissionStockApp.Models.Entities.VehicleBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VehicleBrands");
                });

            modelBuilder.Entity("TransmissionStockApp.Models.Entities.VehicleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("VehicleBrandId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleBrandId", "Name")
                        .IsUnique();

                    b.ToTable("VehicleModels");
                });

            modelBuilder.Entity("TransmissionStockApp.Models.Entities.TransmissionStock", b =>
                {
                    b.HasOne("TransmissionStockApp.Models.Entities.TransmissionBrand", "TransmissionBrand")
                        .WithMany("TransmissionStocks")
                        .HasForeignKey("TransmissionBrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransmissionStockApp.Models.Entities.TransmissionDriveType", "TransmissionDriveType")
                        .WithMany("TransmissionStocks")
                        .HasForeignKey("TransmissionDriveTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TransmissionStockApp.Models.Entities.TransmissionStatus", "TransmissionStatus")
                        .WithMany("TransmissionStocks")
                        .HasForeignKey("TransmissionStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransmissionStockApp.Models.Entities.VehicleBrand", "VehicleBrand")
                        .WithMany("TransmissionStocks")
                        .HasForeignKey("VehicleBrandId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TransmissionStockApp.Models.Entities.VehicleModel", "VehicleModel")
                        .WithMany("TransmissionStocks")
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TransmissionBrand");

                    b.Navigation("TransmissionDriveType");

                    b.Navigation("TransmissionStatus");

                    b.Navigation("VehicleBrand");

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("TransmissionStockApp.Models.Entities.TransmissionStockLocation", b =>
                {
                    b.HasOne("TransmissionStockApp.Models.Entities.StockLocation", "StockLocation")
                        .WithMany("TransmissionStockLocations")
                        .HasForeignKey("StockLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransmissionStockApp.Models.Entities.TransmissionStock", "TransmissionStock")
                        .WithMany("TransmissionStockLocations")
                        .HasForeignKey("TransmissionStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockLocation");

                    b.Navigation("TransmissionStock");
                });

            modelBuilder.Entity("TransmissionStockApp.Models.Entities.VehicleModel", b =>
                {
                    b.HasOne("TransmissionStockApp.Models.Entities.VehicleBrand", "VehicleBrand")
                        .WithMany("Models")
                        .HasForeignKey("VehicleBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleBrand");
                });

            modelBuilder.Entity("TransmissionStockApp.Models.Entities.StockLocation", b =>
                {
                    b.Navigation("TransmissionStockLocations");
                });

            modelBuilder.Entity("TransmissionStockApp.Models.Entities.TransmissionBrand", b =>
                {
                    b.Navigation("TransmissionStocks");
                });

            modelBuilder.Entity("TransmissionStockApp.Models.Entities.TransmissionDriveType", b =>
                {
                    b.Navigation("TransmissionStocks");
                });

            modelBuilder.Entity("TransmissionStockApp.Models.Entities.TransmissionStatus", b =>
                {
                    b.Navigation("TransmissionStocks");
                });

            modelBuilder.Entity("TransmissionStockApp.Models.Entities.TransmissionStock", b =>
                {
                    b.Navigation("TransmissionStockLocations");
                });

            modelBuilder.Entity("TransmissionStockApp.Models.Entities.VehicleBrand", b =>
                {
                    b.Navigation("Models");

                    b.Navigation("TransmissionStocks");
                });

            modelBuilder.Entity("TransmissionStockApp.Models.Entities.VehicleModel", b =>
                {
                    b.Navigation("TransmissionStocks");
                });
#pragma warning restore 612, 618
        }
    }
}
